Portfolio website Contact form
DhuruvSingh/Portfolio-Website-New pull request #4
Opened 2022-07-05 22:40 UTC by DhuruvSingh

### Portfolio: add a contact form and finish the mobile version

- Added Input with Name field accepts up to 30 chars.
- Added Input with Email field accepts only emails.
- Added Input with Message field accepts up to 500 chars.
- All fields have placeholder text.
- All fields have the correct type.
- A user cannot submit the form if one or more of the fields is empty.
- Collect data by using the [Formspree service](https://formspree.io/html).

> Please Review And Give Your Valuable Feedback

2022-07-05 22:53 UTC, tufoinnkuo10 requested changes
Hi @DhuruvSingh 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅form submits successfully
✅figma design well followed

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/l46CxmW82zcQiRghG/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-05 22:53 UTC, tufoinnkuo10 commented on index.html
> +            <button type="submit">Get in touch</button>
- [ ] Great job with the contact section. everything works as expected. nevertheless, kindly add the bottom margin so as to make it look more like the figma version
your version
![Screenshot (207)](https://user-images.githubusercontent.com/65298048/177429673-5ca3fdae-d524-460d-9078-4775ee27c8f1.png)
figma version 
![Screenshot (208)_LI](https://user-images.githubusercontent.com/65298048/177429762-73dcbeab-f5d5-4ccc-b8a5-92ea4c70a7b4.jpg)

2022-07-06 07:25 UTC, muneebulrehman approved these changes
Hi @DhuruvSingh , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Good use of semantic tags.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 07:43 UTC, DhuruvSingh commented
Thank you so much for your valuable feedback @muneebulrehman @tufoinnkuo10

2022-07-06 07:43 UTC, merged